### ISSUE TITLE
greenの場合はvx_gになっていていいと思いますけど、だったらredの場合にもvx_rにしたほうが分かりやすいと思います。

### ISSUE THREAD

**Issue by c0b2103990** [c0b2107909/ProjExD#12]
https://github.com/c0b2107909/ProjExD/blob/9edaf2b1ffc98b795b9180767a36b7abf3df69d6/ex04/dodge_bomb.py#L44

**Comment by c0b2107909** [comment]
修正しました、ありがとうございます。
