### ISSUE TITLE
縦横ライン

### ISSUE THREAD

**Issue by C0B21165** [c0b2107909/ProjExD#25]
https://github.com/c0b2107909/ProjExD/blob/246a917f45acac6e29711ec8722384a5d6f38ad8/ex06/gomoku.py#L74

遠いせいもあったかと思いますが、線が若干細くて薄いように見えたので、もう少しだけ濃くても良いと思いました。

**Comment by c0b2107909** [comment]
修正しました。ありがとうございます。
